### ISSUE TITLE
Any help needed ?

### ISSUE THREAD

**Issue by Clement-Jean** [rollbear/dry-comparisons#4]
I'm really interested by the idea, I would like to help.

**Comment by rollbear** [comment]
Not entirely sure, but maybe. I planned to rewrite the lib after the conference presentations, because it's ironic that the library implementation itself is quite repetitive. However, doing so resulted in filing quite a few compiler bug reports :-( It turns out that compilers aren't good at handling conditional `noexcept` and explicit return type using `decltype` from generalized lambdas. Not good at all.

I'll clean up the current state and push it to a branch later today. I'll ping you when it's there. Then there will be two things. Find work-arounds for compiler bugs :-( and use clang-9 `-ftime-trace` to find compilation time bottlenecks and find faster solutions. https://aras-p.info/blog/2019/01/16/time-trace-timeline-flame-chart-profiler-for-Clang/

**Comment by rollbear** [comment]
So, pushed "as-is" to branch `drier`. There are a number of TODO comments in the test sources that can guide you. Also, clang crashes (9 and trunk). It's reported. If you can find works arounds that'd be cool. I've only been able to test MSVC with compiler-explorer, and it fails with messages i do not understand. If you can find work arounds for that, it'd be cool too.

**Comment by Clement-Jean** [comment]
It seems that its clang's AST that is failing to parse, interesting :smile:

**Comment by offa** [comment]
Does this appear when this library is used in client code or even when compiling the test?

**Comment by Clement-Jean** [comment]
@offa when compiling the code
